/**
 * SeasonAddForm Component
 *
 * Form for creating a new league season. Supports both automatic weekly date
 * generation (starting from a chosen initial date, skipping blocked/holiday
 * dates from the calendar) and manual date entry. Date generation is debounced
 * when the weeks count input changes. Returns a 422 conflict error when the
 * season code already exists.
 */
"use client";

// Import necessary libraries and components
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";
import { toast } from "sonner";
import React from "react";
import { InputDefault } from "@/components/ui/form-input-default";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { DatePickerCustom } from "@/components/ui/date-picker";
import { seasonRoute } from "@/lib/apiRoutes";
import { useMutation } from "@tanstack/react-query";
import { fetchWithSession } from "@/lib/getData";
import { useCalendarData } from "@/hooks/useCalendarData";

// Define the schema for form validation using zod
const seasonFormSchema = z.object({
	seasonCode: z.string().min(1, { message: "Season Code is required." }),
	fiscalYear: z.string().min(1, { message: "Fiscal Year is required." }),
	dates: z.string(),
	isCurrentSeason: z.boolean(),
	desc: z.string().optional(),
});

// Define styles for the form container, checkbox, and input width
const formContainerStyle =
	"p-4 shadow-lg bg-background rounded-lg border border-border";
const checkboxWidth = "h-5 w-5";
const inputWidth = "w-24";

/**
 * SeasonAddForm creates a new season record with a code, fiscal year, dates, and settings.
 *
 * @param onClose - Callback to close the containing dialog
 * @param onRefresh - Callback to reload the parent data table
 */
export default function SeasonAddForm({
	onClose,
	onRefresh,
}: {
	onClose: () => void;
	onRefresh: () => void;
}) {
	// Define state variables for auto-generating dates, number of weeks, initial date, and dates
	const [autoGenerateDates, setAutoGenerateDates] = React.useState(true);
	const [howManyWeeks, setHowManyWeeks] = React.useState(14);
	const [howManyWeeksInput, setHowManyWeeksInput] = React.useState("14");
	const [initialDate, setInitialDate] = React.useState<Date | undefined>(undefined);
	const [dates, setDates] = React.useState<string>();
	const [manualDates, setManualDates] = React.useState<(string | null)[]>([]);
	const [seasonCodeExists, setSeasonCodeExists] = React.useState(false);

	// Fetch blocked dates from calendar
	const currentYear = initialDate?.getFullYear() || new Date().getFullYear();
	const { data: calendarData } = useCalendarData(currentYear);

	// Convert calendar data to blocked dates set for quick lookup
	const blockedDatesSet = React.useMemo(() => {
		if (!calendarData) return new Set<string>();
		return new Set(
			calendarData.map(item => {
				const date = new Date(item.date);
				date.setHours(0, 0, 0, 0);
				return date.toDateString();
			})
		);
	}, [calendarData]);

	// Convert to Date array for DatePickerCustom
	const disabledDates = React.useMemo(() => {
		if (!calendarData) return [];
		return calendarData.map(item => new Date(item.date));
	}, [calendarData]);

	const mutation = useMutation({
		mutationFn: async (values: z.infer<typeof seasonFormSchema>) => {
			const formattedDates = JSON.parse(dates || "[]").reduce(
				(acc: { [key: string]: string }, date: string, index: number) => {
					acc[`Date${index + 1}`] = date;
					return acc;
				},
				{}
			);
			values.dates = JSON.stringify(formattedDates);
			const response = await fetchWithSession(seasonRoute, {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify(values),
			});
			if (!response.ok) {
				if (response.status === 422) {
					setSeasonCodeExists(true);
				}
				const errorData = await response.json();
				throw new Error(
					errorData?.message ||
						`HTTP error! status: ${response.status}`
				);
			}
			return await response.json();
		},
		onSuccess: (results) => {
			toast.success("Successfully submitted the form!");
			form.reset();
			console.log("Form submitted successfully!", results);
			onClose();
			onRefresh();
		},
		onError: (error: unknown) => {
			console.error("Form submission error", error);
			toast.error(
				`Failed to submit the form: ${
					(error as Error).message || "Please try again."
				}`
			);
		},
	});

	// Initialize the form using react-hook-form and zodResolver
	const form = useForm<z.infer<typeof seasonFormSchema>>({
		resolver: zodResolver(seasonFormSchema),
		defaultValues: {
			seasonCode: "",
			fiscalYear: "",
			dates: "",
			isCurrentSeason: true,
			desc: "",
		},
	});

	// Reset form and all state when component mounts to ensure clean state
	React.useEffect(() => {
		setSeasonCodeExists(false);
		setAutoGenerateDates(true);
		setHowManyWeeks(14);
		setHowManyWeeksInput("14");
		setInitialDate(undefined);
		setDates(undefined);
		setManualDates([]);
		form.reset({
			seasonCode: "",
			fiscalYear: "",
			dates: "",
			isCurrentSeason: true,
			desc: "",
		});
	}, [form]);

	// Debounce effect for howManyWeeks input
	React.useEffect(() => {
		const timer = setTimeout(() => {
			const value = parseInt(howManyWeeksInput);
			if (!isNaN(value) && value > 0 && value <= 54) {
				setHowManyWeeks(value);
			} else if (value > 54) {
				setHowManyWeeks(54);
			} else if (howManyWeeksInput === "") {
				// Don't update if field is empty (user is still typing)
				return;
			} else {
				setHowManyWeeks(14); // Default value
			}
		}, 500); // 500ms delay

		return () => clearTimeout(timer);
	}, [howManyWeeksInput]);

	// Use effect to auto-generate dates based on initial date and number of weeks
	React.useEffect(() => {
		if (autoGenerateDates && initialDate) {
			const generatedDates: string[] = [];
			let currentDate = new Date(initialDate);
			currentDate.setHours(0, 0, 0, 0);
			
			for (let i = 0; i < howManyWeeks; i++) {
				let daysToAdd = i === 0 ? 0 : 7;
				
				// Check if current date is blocked, if so move to next available day
				let daysShifted = 0;
				while (blockedDatesSet.has(currentDate.toDateString())) {
					currentDate.setDate(currentDate.getDate() + 1);
					daysShifted++;
				}
				
				const formattedDate = currentDate.toLocaleDateString("en-US");
				generatedDates.push(formattedDate);
				
				// Move to next week, but compensate for any shifts
				// If we shifted by 1 day due to a blocked date, add only 6 days instead of 7
				if (i < howManyWeeks - 1) {
					currentDate = new Date(currentDate);
					currentDate.setDate(currentDate.getDate() + (7 - daysShifted));
				}
			}
			setDates(JSON.stringify(generatedDates));
			setManualDates([]);
		}
	}, [autoGenerateDates, howManyWeeks, initialDate, blockedDatesSet]);

	// Effect to initialize date to first non-blocked date
	React.useEffect(() => {
		if (!initialDate && blockedDatesSet.size >= 0) {
			const today = new Date();
			today.setHours(0, 0, 0, 0);
			
			const checkDate = new Date(today);
			while (blockedDatesSet.has(checkDate.toDateString())) {
				checkDate.setDate(checkDate.getDate() + 1);
			}
			setInitialDate(checkDate);
		}
	}, [initialDate, blockedDatesSet]);

	// Effect to adjust initial date if it's blocked (when manually changed)
	React.useEffect(() => {
		if (initialDate && blockedDatesSet.size > 0) {
			const checkDate = new Date(initialDate);
			checkDate.setHours(0, 0, 0, 0);
			
			// If the current initial date is blocked, find the next available date
			if (blockedDatesSet.has(checkDate.toDateString())) {
				const newDate = new Date(checkDate);
				while (blockedDatesSet.has(newDate.toDateString())) {
					newDate.setDate(newDate.getDate() + 1);
				}
				// Only update if it's actually different
				if (newDate.toDateString() !== checkDate.toDateString()) {
					setInitialDate(newDate);
				}
			}
		}
	}, [blockedDatesSet, initialDate]);

	// Separate effect to sync manual dates to dates string
	React.useEffect(() => {
		if (!autoGenerateDates && manualDates.length > 0) {
			const validDates = manualDates.filter(d => d !== null);
			if (validDates.length === manualDates.length) {
				setDates(JSON.stringify(manualDates));
			} else {
				setDates("");
			}
		} else if (!autoGenerateDates && manualDates.length === 0) {
			setDates("");
		}
	}, [manualDates, autoGenerateDates]);

	// Handle date change for manual date selection
	const handleDateChange = (
		selectedDate: Date | undefined,
		index: number
	) => {
		if (selectedDate) {
			if (autoGenerateDates) {
				const updatedDates = JSON.parse(dates || "[]");
				updatedDates[index] = selectedDate.toLocaleDateString("en-US");
				for (let i = index + 1; i < updatedDates.length; i++) {
					const previousDate = new Date(updatedDates[i - 1]);
					previousDate.setDate(previousDate.getDate() + 7);
					updatedDates[i] = previousDate.toLocaleDateString("en-US");
				}
				setDates(JSON.stringify(updatedDates));
			} else {
				const updatedManualDates = [...manualDates];
				updatedManualDates[index] = selectedDate.toLocaleDateString("en-US");
				setManualDates(updatedManualDates);
			}
		}
	};

	// Add a new empty date tile
	const handleAddDate = () => {
		setManualDates([...manualDates, null]);
	};

	// Check if all manual dates are filled
	const allManualDatesFilled = () => {
		if (!autoGenerateDates && manualDates.length > 0) {
			return manualDates.every(date => date !== null);
		}
		return true;
	};

	async function onSubmit(values: z.infer<typeof seasonFormSchema>) {
		setSeasonCodeExists(false);
		
		// Validate manual dates
		if (!autoGenerateDates && manualDates.length > 0 && !allManualDatesFilled()) {
			toast.error("Please fill in all date tiles before submitting.");
			return;
		}
		
		// Update dates from manual dates if not auto-generating
		if (!autoGenerateDates && manualDates.length > 0) {
			setDates(JSON.stringify(manualDates));
		}
		mutation.mutate(values);
	}

	// Render the form
	return (
		<Form {...form}>
			<form
				onSubmit={form.handleSubmit(onSubmit)}
				className="space-y-6 mx-auto max-w-2xl"
			>
				<div className={formContainerStyle}>
					<h2 className="text-2xl font-semibold mb-6">Add Season</h2>
					
					{/* Season Code and Fiscal Year Row */}
					<div className="grid grid-cols-2 gap-4 mb-4">
						<div>
							<InputDefault
								control={form.control}
								name="seasonCode"
								label="Season Code *"
							/>
							{seasonCodeExists && (
								<p className="text-red-500 text-sm mt-1">
									Season Code already exists
								</p>
							)}
						</div>
						<InputDefault
							control={form.control}
							name="fiscalYear"
							label="Fiscal Year *"
						/>
					</div>

					{/* Current Season Checkbox */}
					<FormField
						control={form.control}
						name="isCurrentSeason"
						render={({ field }) => (
							<FormItem className="flex flex-row items-center space-x-3 mb-4">
								<FormControl>
									<Checkbox
										id="isCurrentSeasonCheckbox"
										checked={field.value}
										onCheckedChange={field.onChange}
										className={checkboxWidth}
									/>
								</FormControl>
								<Label
									className="whitespace-nowrap !mt-0 cursor-pointer"
									htmlFor="isCurrentSeasonCheckbox"
								>
									Current Season
								</Label>
							</FormItem>
						)}
					/>

					{/* Description */}
					<FormField
						control={form.control}
						name="desc"
						render={({ field }) => (
							<FormItem className="mb-4">
								<FormLabel>Description</FormLabel>
								<FormControl>
									<Textarea
										placeholder="Additional Data Here..."
										{...field}
										className="min-h-[100px]"
									/>
								</FormControl>
								<FormMessage />
							</FormItem>
						)}
					/>

					<Separator className="my-6" />

					{/* Automatically Generate Dates */}
					<div className="flex items-center space-x-3 mb-4">
						<Checkbox
							checked={autoGenerateDates}
							onCheckedChange={(checked: boolean) =>
								setAutoGenerateDates(checked)
							}
							className={checkboxWidth}
							id="generateDates"
						/>
						<Label
							className="whitespace-nowrap cursor-pointer !mt-0"
							htmlFor="generateDates"
						>
							Automatically generate dates
						</Label>
					</div>

					{autoGenerateDates ? (
						<>
							{/* How Many Weeks */}
							<div className="mb-4">
								<Label
									className="block mb-2"
									htmlFor="howManyWeeks"
								>
									How Many Weeks?
								</Label>
								<Input
									id="howManyWeeks"
									type="number"
									value={howManyWeeksInput}
									min={1}
									max={54}
									onChange={(e) => {
										setHowManyWeeksInput(e.target.value);
									}}
									className={inputWidth}
								/>
							</div>

							{/* Initial Date */}
							<div className="mb-6">
								<Label
									className="block mb-2"
									htmlFor="initialDate"
								>
									Initial Date
								</Label>
								{initialDate ? (
									<DatePickerCustom
										onDateChange={(date) => {
											if (date) {
												setInitialDate(date);
											}
										}}
										initialMonth={initialDate}
										dateSelected={initialDate}
										showInput={true}
										disabledDates={disabledDates}
									/>
								) : (
									<div className="text-sm text-muted-foreground">Loading...</div>
								)}
							</div>

							{/* Generated Dates Tiles */}
							<div className="mt-6">
								<Label className="block mb-3 text-sm font-medium text-muted-foreground">
									Generated Dates
								</Label>
								<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 max-h-[400px] overflow-y-auto pr-2">
									{(dates
										? JSON.parse(dates)
										: []
									).map(
										(
											date: string,
											index: number
										) => (
											<div 
												key={index}
												className="group relative p-3 border border-border rounded-lg bg-card hover:border-primary/50 transition-all overflow-hidden"
											>
												<div className="group-hover:blur-sm transition-all">
													<div className="text-xs font-medium text-muted-foreground mb-2">
														Date {index + 1}
													</div>
													<div className="text-sm font-semibold">
														{date}
													</div>
												</div>
												<div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
													<DatePickerCustom
														onDateChange={(selectedDate) => {
															handleDateChange(selectedDate, index);
														}}
														initialMonth={new Date(date)}
														dateSelected={new Date(date)}
														disabledDates={disabledDates}
													/>
												</div>
											</div>
										)
									)}
								</div>
							</div>
						</>
					) : (
						<>
							{/* Manual Date Addition */}
							<div className="mt-6">
								<div className="flex justify-between items-center mb-3">
									<Label className="text-sm font-medium text-muted-foreground">
										Manual Dates
									</Label>
									<Button
										type="button"
										variant="outline"
										onClick={handleAddDate}
										className="hover:bg-muted border-border text-foreground"
									>
										Add Date
									</Button>
								</div>
								{manualDates.length > 0 ? (
									<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 max-h-[400px] overflow-y-auto pr-2">
										{manualDates.map((date, index) => (
											<div 
												key={index}
												className={`group relative p-3 border rounded-lg bg-card hover:border-primary/50 transition-all overflow-hidden ${
													date === null ? 'border-red-500' : 'border-border'
												}`}
											>
												<div className="group-hover:blur-sm transition-all">
													<div className="text-xs font-medium text-muted-foreground mb-2">
														Date {index + 1}
													</div>
													<div className="text-sm font-semibold">
														{date || 'Click to add date'}
													</div>
												</div>
												<div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
													<DatePickerCustom
														onDateChange={(selectedDate) => {
															handleDateChange(selectedDate, index);
														}}
														initialMonth={date ? new Date(date) : new Date()}
														dateSelected={date ? new Date(date) : undefined}													disabledDates={disabledDates}													/>
												</div>
											</div>
										))}
									</div>
								) : (
									<div className="text-center py-8 text-muted-foreground">
										Click "Add Date" to create date tiles
									</div>
								)}
							</div>
						</>
					)}
				</div>

				<div className="flex justify-center">
					<Button variant="outline" type="submit" className="hover:bg-muted border-border text-foreground px-8">
						Add
					</Button>
				</div>
			</form>
		</Form>
	);
}
