"use client";

// Import necessary libraries and components
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";
import { toast } from "sonner";
import React from "react";
import { InputDefault } from "@/components/ui/form-input-default";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { DatePicker } from "@/components/ui/date-picker";
import { seasonRoute } from "@/lib/apiRoutes";

// Define the schema for form validation using zod
const seasonFormSchema = z.object({
	seasonCode: z.string().min(1, { message: "Season Code is required." }),
	fiscalYear: z.string().min(1, { message: "Fiscal Year is required." }),
	dates: z.string(),
	isCurrentSeason: z.boolean(),
	desc: z.string().optional(),
});

// Define styles for the form container, checkbox, and input width
const formContainerStyle =
	"p-4 shadow-lg bg-white rounded-lg border border-gray-300";
const checkboxWidth = "h-5 w-5";
const inputWidth = "w-24";

// Define the SeasonAddForm component
export default function SeasonAddForm({
	onClose,
	onRefresh,
}: {
	onClose: () => void;
	onRefresh: () => void;
}) {
	// Define state variables for auto-generating dates, number of weeks, initial date, and dates
	const [autoGenerateDates, setAutoGenerateDates] = React.useState(true);
	const [howManyWeeks, setHowManyWeeks] = React.useState(14);
	const [initialDate, setInitialDate] = React.useState(new Date());
	const [dates, setDates] = React.useState<string>();

	// Initialize the form using react-hook-form and zodResolver
	const form = useForm<z.infer<typeof seasonFormSchema>>({
		resolver: zodResolver(seasonFormSchema),
		defaultValues: {
			seasonCode: "",
			fiscalYear: "",
			dates: "",
			isCurrentSeason: true,
			desc: "",
		},
	});

	// Use effect to auto-generate dates based on initial date and number of weeks
	React.useEffect(() => {
		if (autoGenerateDates) {
			const generatedDates: string[] = [];
			const currentDate = new Date(initialDate);
			for (let i = 0; i < howManyWeeks; i++) {
				generatedDates.push(currentDate.toISOString().split("T")[0]);
				currentDate.setDate(currentDate.getDate() + 7);
			}
			console.log(generatedDates);
			setDates(JSON.stringify(generatedDates));
		} else {
			setDates("");
		}
	}, [autoGenerateDates, howManyWeeks, initialDate]);

	// Handle date change for manual date selection
	const handleDateChange = (
		selectedDate: Date | undefined,
		index: number
	) => {
		if (selectedDate) {
			const updatedDates = JSON.parse(dates || "[]");
			updatedDates[index] = selectedDate.toISOString().split("T")[0];
			for (let i = index + 1; i < updatedDates.length; i++) {
				const previousDate = new Date(updatedDates[i - 1]);
				previousDate.setDate(previousDate.getDate() + 7);
				updatedDates[i] = previousDate.toISOString().split("T")[0];
			}
			setDates(JSON.stringify(updatedDates));
		}
	};

	// Define the onSubmit function to handle form submission
	async function onSubmit(values: z.infer<typeof seasonFormSchema>) {
		const formattedDates = JSON.parse(dates || "[]").reduce(
			(acc: { [key: string]: string }, date: string, index: number) => {
				acc[`Date${index + 1}`] = new Date(date).toLocaleDateString(
					"en-US"
				);
				return acc;
			},
			{}
		);
		values.dates = JSON.stringify(formattedDates);
		console.log("Submitting form with values", values);
		try {
			const response = await fetch(seasonRoute, {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify(values),
			});

			if (!response.ok) {
				const errorData = await response.json();
				throw new Error(
					errorData?.message ||
						`HTTP error! status: ${response.status}`
				);
			}

			const results = await response.json();
			toast.success("Successfully submitted the form!");

			// Reset form and state
			form.reset();

			console.log("Form submitted successfully!", results);
			onClose(); // Close the form
			onRefresh(); // Refresh the datatable with the place API route
		} catch (error) {
			console.error("Form submission error", error);
			toast.error(
				`Failed to submit the form: ${
					(error as Error).message || "Please try again."
				}`
			);
		}
	}

	// Render the form
	return (
		<Form {...form}>
			<form
				onSubmit={form.handleSubmit(onSubmit)}
				className="space-y-4 mx-auto"
			>
				<div className="flex space-x-4">
					<div className={formContainerStyle}>
						<FormField
							control={form.control}
							name="isCurrentSeason"
							render={({ field }) => (
								<FormItem>
									<Label
										className="whitespace-nowrap pr-2"
										htmlFor="isCurrentSeasonCheckbox"
									>
										Current Season?
									</Label>
									<FormControl>
										<Checkbox
											id="isCurrentSeasonCheckbox"
											checked={field.value}
											onCheckedChange={field.onChange}
											className={checkboxWidth}
										/>
									</FormControl>
								</FormItem>
							)}
						/>
						<div className="flex space-x-4">
							<InputDefault
								control={form.control}
								name="seasonCode"
								label="Season Code *"
								customClass={inputWidth}
							/>
							<InputDefault
								control={form.control}
								name="fiscalYear"
								label="Fiscal Year *"
								customClass={inputWidth}
							/>
						</div>
						<div className="flex items-start space-x-2">
							<Label
								className="whitespace-nowrap"
								htmlFor="generateDates"
							>
								Automatically Generate Dates? - Manual Entry
								Coming Later
							</Label>
							<Checkbox
								checked={autoGenerateDates}
								onCheckedChange={(checked: boolean) =>
									setAutoGenerateDates(checked)
								}
								className={checkboxWidth}
								id="generateDates"
								disabled
							/>
						</div>
						{autoGenerateDates && (
							<>
								<Label
									className={`whitespace-nowrap`}
									htmlFor="howManyWeeks"
								>
									{" "}
									How Many Weeks?{" "}
								</Label>
								<Input
									id="howManyWeeks"
									type="number"
									placeholder={howManyWeeks.toString()}
									min={1}
									max={2}
									onChange={(e) => {
										const value = parseInt(e.target.value);
										if (
											!isNaN(value) &&
											value > 0 &&
											value <= 54
										) {
											setHowManyWeeks(value);
										} else if (value > 54) {
											setHowManyWeeks(54); //max value
										} else {
											setHowManyWeeks(10); // Default value
										}
									}}
									className={`${inputWidth}`}
								/>
								<Label
									className="whitespace-nowrap"
									htmlFor="initialDate"
								>
									{" "}
									Initial Date{" "}
								</Label>
								<Input
									id="initialDate"
									type="date"
									value={
										initialDate.toISOString().split("T")[0]
									}
									onChange={(e) => {
										const value = new Date(e.target.value);
										if (!isNaN(value.getTime())) {
											setInitialDate(value);
										}
									}}
								/>
								<div className="mt-2 max-w-[65vw] overflow-x-auto">
									<Label className="whitespace-nowrap text-gray-500">
										Generated Dates
									</Label>
									<Separator className="my-2" />
									<table className="max-w-[65vw] divide-y divide-gray-200 overflow-auto">
										<thead className="bg-gray-50">
											<tr>
												{dates &&
													Array.isArray(
														JSON.parse(dates)
													) &&
													JSON.parse(dates).map(
														(
															date: string,
															index: number
														) => (
															<th
																key={index}
																scope="col"
																className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider whitespace-nowrap"
															>
																Date {index + 1}
																<DatePicker
																	onDateChange={(
																		date
																	) =>
																		handleDateChange(
																			date,
																			index
																		)
																	}
																	initialMonth={
																		new Date(
																			date
																		)
																	}
																	dateSelected={
																		new Date(
																			date
																		)
																	}
																/>
															</th>
														)
													)}
											</tr>
										</thead>
										<tbody className="bg-white divide-y divide-gray-200">
											<tr>
												{dates &&
													Array.isArray(
														JSON.parse(dates)
													) &&
													JSON.parse(dates).map(
														(
															date: string,
															index: number
														) => (
															<td
																key={index}
																className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 cursor-pointer"
															>
																{date}
															</td>
														)
													)}
											</tr>
										</tbody>
									</table>
								</div>
							</>
						)}
						<FormField
							control={form.control}
							name="desc"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Description</FormLabel>
									<FormControl>
										<Textarea
											placeholder="Additional Data Here..."
											{...field}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
					</div>
				</div>
				<div className="flex justify-center">
					<Button type="submit">Add</Button>
				</div>
			</form>
		</Form>
	);
}
